"""initial schema

Revision ID: 1c887f9c3d81
Revises: 
Create Date: 2026-05-29 23:25:01.597636
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1c887f9c3d81'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('info_xml', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('settings_xml', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('category', 'tag', 'rating', name='label_type'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('storage_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backend', sa.Enum('local', 's3', 'gcs', name='storage_backend'), nullable=False),
    sa.Column('bucket', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backend', 'bucket', 'key', name='uq_storage_locator')
    )
    op.create_table('commission_artists',
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commission_id', 'artist_id')
    )
    op.create_table('commission_characters',
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commission_id', 'character_id')
    )
    op.create_table('commission_labels',
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commission_id', 'label_id')
    )
    op.create_table('commission_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('rating', sa.Enum('general', 'mature', 'adult', name='rating'), nullable=False),
    sa.Column('cover_file_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cover_file_id'], ['commission_files.id'], name='fk_meta_cover_file', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commission_id')
    )
    op.create_table('commission_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_detached', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commission_id', 'position', name='uq_node_position')
    )
    op.create_table('commission_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('storage_object_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_image', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('focal_x', sa.Float(), nullable=True),
    sa.Column('focal_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['commission_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_object_id'], ['storage_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commission_files')
    op.drop_table('commission_nodes')
    op.drop_table('commission_metadata')
    op.drop_table('commission_labels')
    op.drop_table('commission_characters')
    op.drop_table('commission_artists')
    op.drop_table('storage_objects')
    op.drop_table('labels')
    op.drop_table('commissions')
    op.drop_table('characters')
    op.drop_table('artists')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
