"""Populate the dev database with sample commissions and placeholder cover images.

Run: uv run python -m app.seed
"""

from __future__ import annotations

import io
import random
from datetime import datetime

from PIL import Image, ImageDraw

from app.db import SessionLocal
from app.models import (
    Commission,
    CommissionFile,
    Rating,
    StorageBackend,
    StorageObject,
)
from app.schemas import CommissionCreate
from app.api.v1 import crud
from app.storage import get_storage

CATS = ["Chibi", "Avatar", "Monochrome", "Reference", "Weapon", "Other"]
TAGS = ["background", "co-commission", "差分", "watermark", "expression-sheet"]
CHARS = ["Heiyao", "Banzhi", "Gengzi", "Dileselon", "Aki", "Mira"]
ARTISTS = ["Natsume Ryuhane", "yuzuki", "板纸", "ToumeiSheep", "凉子"]
TITLES = [
    "Banzhi & Shouza — chibi pair", "Chibi w/ Dileselon", "Cut tail study",
    "Greatsword — watermark", "Avatar set", "Totem motif", "Lineart pass",
    "Color rough", "Expression sheet", "Reference: outfit A", "Background: forest",
    "Mira ref", "Aki — chibi pair", "Heiyao — portrait", "Twin chibis", "Wing ref",
]
RATIOS = [(3, 4), (4, 5), (1, 1), (4, 3), (2, 3), (3, 2)]
PALETTE = ["#e7f0ed", "#efeae0", "#f1e3df", "#e6ecf3", "#ece5f2", "#f3f1ec"]
NODE_NAMES = ["Sketching", "Lineart", "Color", "Delivered"]


def _placeholder_png(w: int, h: int, title: str, color: str) -> bytes:
    img = Image.new("RGB", (w, h), color)
    d = ImageDraw.Draw(img)
    d.rectangle([4, 4, w - 5, h - 5], outline="#37352f", width=2)
    d.text((16, 16), f"{w}×{h}", fill="#37352f")
    d.text((16, h - 28), title[:24], fill="#37352f")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def run(n: int = 16) -> None:
    rng = random.Random(7)
    db = SessionLocal()
    storage = get_storage()
    try:
        if db.query(Commission).count() > 0:
            print("Database already has commissions; skipping seed.")
            return

        for i in range(n):
            ar = rng.choice(RATIOS)
            data = CommissionCreate(
                title=TITLES[i % len(TITLES)],
                description="Sample commission generated by the dev seed script.",
                completed_at=datetime(2024, rng.randint(1, 12), rng.randint(1, 28)).date(),
                rating=rng.choice([Rating.general, Rating.general, Rating.mature, Rating.adult]),
                category_names=rng.sample(CATS, k=rng.randint(1, 2)),
                tag_names=rng.sample(TAGS, k=rng.randint(0, 2)),
                character_names=rng.sample(CHARS, k=rng.randint(1, 2)),
                artist_names=rng.sample(ARTISTS, k=rng.randint(1, 2)),
                node_names=NODE_NAMES,
            )
            commission = crud.create_commission(db, data)

            delivered = next(n for n in commission.nodes if n.name == "Delivered")
            w = 600
            h = round(w * ar[1] / ar[0])
            png = _placeholder_png(w, h, data.title, rng.choice(PALETTE))
            key = f"commissions/{commission.id}/nodes/{delivered.id}/cover.png"
            stored = storage.save(key, png)
            obj = StorageObject(
                backend=StorageBackend(stored.backend),
                bucket=stored.bucket,
                key=stored.key,
                size_bytes=stored.size_bytes,
                checksum=stored.checksum,
            )
            db.add(obj)
            db.flush()
            file = CommissionFile(
                node_id=delivered.id,
                storage_object_id=obj.id,
                position=0,
                format="png",
                is_image=True,
                width=w,
                height=h,
                focal_x=0.5,
                focal_y=0.4,
            )
            db.add(file)
            db.flush()
            commission.meta.cover_file_id = file.id
            db.commit()
            print(f"  seeded #{commission.id}: {data.title}")

        print(f"Seeded {n} commissions.")
    finally:
        db.close()


if __name__ == "__main__":
    run()
